# Book settings
title: 統計建模技法
author: Po-Hsien Huang

execute:
  execute_notebooks: auto

latex:
  latex_documents:
    targetname: book.tex

html:
  extra_navbar:

repository:
  url                       : https://github.com/psyphh/tism  # Online location of your book
  path_to_book              : tism/  # Optional path to your book, relative to the repository root
  branch                    : master


launch_buttons:
  colab_url: "https://colab.research.google.com"
